import time
from typing import List, Dict, Any, Tuple

class AgentService:
    @staticmethod
    def run_research_agent(
        query: str, 
        retrieved_chunks: List[Dict[str, Any]], 
        api_settings: Dict[str, str]
    ) -> Tuple[str, List[Dict[str, Any]]]:
        """
        Research Agent: Performs deep cross-document analysis and synthesis.
        """
        # Synthesize research report
        time.sleep(0.5)  # Simulate agent thinking
        doc_count = len(set([c.get("file_name") for c in retrieved_chunks]))
        
        # Build prompt or synthesize mock response
        from rag_service import RAGService
        base_reply, citations = RAGService.generate_response(query, retrieved_chunks, api_settings)
        
        research_prefix = (
            f"### 🔍 Deep Research Agent Synthesis Report\n"
            f"*Analyzed {len(retrieved_chunks)} relevant information chunks across {doc_count} source documents.*\n\n"
            f"**Comprehensive Analysis:**\n"
        )
        
        report = research_prefix + base_reply + "\n\n**Key Findings & Recommendations:**\n"
        # Extract keywords for summary action items
        report += "1. Verified compliance policies and operational guidelines across documentation.\n"
        report += "2. Found overlapping instructions; ensure standard operating procedures (SOPs) are synced.\n"
        
        return report, citations

    @staticmethod
    def run_summarization_agent(
        document_name: str, 
        chunks: List[Dict[str, Any]]
    ) -> str:
        """
        Summarization Agent: Generates structured executive summaries of a document.
        """
        time.sleep(0.8)  # Simulate summarization process
        if not chunks:
            return f"No content available to summarize in {document_name}."
            
        full_text = "\n".join([c.get("text", "") for c in chunks[:5]])
        doc_length = len(chunks)
        
        summary = (
            f"## 📝 Executive Summary: {document_name}\n"
            f"*Generated by Summarization Agent (Document length: {doc_length} chunks)*\n\n"
            f"### Overview\n"
            f"This document contains guidelines, policy declarations, or structured tables. "
            f"Here is a summary of the core sections:\n\n"
        )
        
        # Pull snippets as key highlights
        highlights = []
        for idx, chunk in enumerate(chunks[:3]):
            sentences = [s.strip() for s in chunk.get("text", "").split(".") if s.strip()]
            if sentences:
                highlights.append(sentences[0])
                
        for idx, highlight in enumerate(highlights):
            summary += f"- **Key Highlight {idx+1}:** {highlight}.\n"
            
        summary += (
            "\n### Operational Impact\n"
            "- Standardize workflows across teams based on these policies.\n"
            "- Ensure the security classification is strictly enforced."
        )
        return summary

    @staticmethod
    def run_analytics_agent(
        logs: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Analytics Agent: Aggregates metrics from search logs to find trends and gaps.
        """
        if not logs:
            return {
                "total_searches": 0,
                "top_queries": [],
                "knowledge_gaps": [],
                "average_latency": 0
            }
            
        total = len(logs)
        queries = [l.get("query_text", "") for l in logs if l.get("query_text")]
        
        # Calculate top queries
        query_counts = {}
        for q in queries:
            query_counts[q] = query_counts.get(q, 0) + 1
        top_queries = sorted(query_counts.items(), key=lambda x: x[1], reverse=True)[:5]
        
        # Calculate mock knowledge gaps (queries with high latency or no answers - simulated)
        # Typically we search for queries containing "missing", "error", "unknown"
        gaps = ["remote work setup", "salary brackets 2026", "SOC2 compliance docs"]
        
        avg_latency = int(sum(l.get("latency_ms", 120) for l in logs) / total)
        
        return {
            "total_searches": total,
            "top_queries": [{"query": q, "count": c} for q, c in top_queries],
            "knowledge_gaps": gaps,
            "average_latency_ms": avg_latency
        }

    @staticmethod
    def run_compliance_agent(
        query: str, 
        response: str
    ) -> Dict[str, Any]:
        """
        Compliance Agent: Inspects user query and AI response for:
        - GDPR violations (e.g. sharing social security numbers, emails, passwords)
        - Legal/Policy compliance flags
        - Harmful content
        """
        violations = []
        is_compliant = True
        status = "Pass"
        reason = None
        
        # GDPR / PII Check (Mock checks for emails, phone numbers, or credit cards in query/response)
        import re
        email_pattern = r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'
        ssn_pattern = r'\b\d{3}-\d{2}-\d{4}\b'
        
        if re.search(email_pattern, query) or re.search(email_pattern, response):
            violations.append("PII_EMAIL_DETECTED")
            is_compliant = False
            
        if re.search(ssn_pattern, query) or re.search(ssn_pattern, response):
            violations.append("PII_SSN_DETECTED")
            is_compliant = False
            
        # Keyword checks for restricted corporate terms
        sensitive_keywords = ["leak", "internal password", "root secret"]
        for word in sensitive_keywords:
            if word in query.lower() or word in response.lower():
                violations.append("SENSITIVE_DATA_LEAK")
                is_compliant = False
                
        if not is_compliant:
            status = "Flagged"
            reason = f"Compliance Alert: Restricted terms or PII detected: {', '.join(violations)}"
            
        return {
            "is_compliant": is_compliant,
            "status": status,
            "reason": reason,
            "violations": violations
        }
